version: '3.8'

services:
  galapass:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: galapass
    ports:
      - "8080:8080"
    networks:
      - galanet

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - galapass
    networks:
      - galanet

networks:
  galanet:
    driver: bridge
