version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: galapass-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
      POSTGRES_HOST_AUTH_METHOD: "md5"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U galapass_user -d galapass_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - galanet

  galapass:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: galapass
    restart: always
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SECRET_KEY: ${SECRET_KEY}
      CLOUD_NAME: ${CLOUD_NAME}
      CLOUD_API_KEY: ${CLOUD_API_KEY}
      CLOUD_SECRET: ${CLOUD_SECRET}
      CLIENT_ID: ${CLIENT_ID}
    depends_on:
      - postgres
    networks:
      - galanet

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - galapass
    networks:
      - galanet

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: galapass-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@galapass.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - galanet

volumes:
  postgres_data:
  pgadmin_data:

networks:
  galanet:
    driver: bridge
